//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeManager.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutButtonText {
            get {
                return ResourceManager.GetString("AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This simple application will help you to control your finances and budget. 
        ///Available features:
        ///- Dynamic categories
        ///- Categorized operations
        ///- Different currencies and conversion operations
        ///- Statistics
        ///- World trade currency rates
        ///- Dynamic tiles
        ///- Flexible UI based on Microsoft Metro styles.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account:.
        /// </summary>
        public static string AccountHeader {
            get {
                return ResourceManager.GetString("AccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with the same name already exist.
        /// </summary>
        public static string AccountNameErrorText {
            get {
                return ResourceManager.GetString("AccountNameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountPageTitle {
            get {
                return ResourceManager.GetString("AccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts and Planing.
        /// </summary>
        public static string AccountsButtonText {
            get {
                return ResourceManager.GetString("AccountsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButtonShortText {
            get {
                return ResourceManager.GetString("AddButtonShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with the same name already exist.
        /// </summary>
        public static string AddFailedMessage {
            get {
                return ResourceManager.GetString("AddFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string AllTimeButtonText {
            get {
                return ResourceManager.GetString("AllTimeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string AmountHeader {
            get {
                return ResourceManager.GetString("AmountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter answer:.
        /// </summary>
        public static string AnswerHeader {
            get {
                return ResourceManager.GetString("AnswerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME MANAGER.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string AttentionCaption {
            get {
                return ResourceManager.GetString("AttentionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BalanceTabHeader {
            get {
                return ResourceManager.GetString("BalanceTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string BaseAccountName {
            get {
                return ResourceManager.GetString("BaseAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string BudgetButtonText {
            get {
                return ResourceManager.GetString("BudgetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include to monthly budget.
        /// </summary>
        public static string BudgetCategoryHeader {
            get {
                return ResourceManager.GetString("BudgetCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget:.
        /// </summary>
        public static string BudgetHeader {
            get {
                return ResourceManager.GetString("BudgetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string BudgetPageHeader {
            get {
                return ResourceManager.GetString("BudgetPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string BuyHeader {
            get {
                return ResourceManager.GetString("BuyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories sort order:.
        /// </summary>
        public static string CategoriesSortOrderHeader {
            get {
                return ResourceManager.GetString("CategoriesSortOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string CategoryHeader {
            get {
                return ResourceManager.GetString("CategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryPageTitle {
            get {
                return ResourceManager.GetString("CategoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, change your password or turn off password protection..
        /// </summary>
        public static string ChangePasswordMessage {
            get {
                return ResourceManager.GetString("ChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear amount:.
        /// </summary>
        public static string ClearAmountHeader {
            get {
                return ResourceManager.GetString("ClearAmountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear database.
        /// </summary>
        public static string ClearDatabaseButtonText {
            get {
                return ResourceManager.GetString("ClearDatabaseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string ClearDatabaseCaption {
            get {
                return ResourceManager.GetString("ClearDatabaseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all data?.
        /// </summary>
        public static string ClearDatabaseMessage {
            get {
                return ResourceManager.GetString("ClearDatabaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string ConfirmPasswordHeader {
            get {
                return ResourceManager.GetString("ConfirmPasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts:
        ///Any questions, suggestions and bug reports you can send to our support:.
        /// </summary>
        public static string ContactsText {
            get {
                return ResourceManager.GetString("ContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        public static string ConversionPageTitle {
            get {
                return ResourceManager.GetString("ConversionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        public static string ConversionTabHeader {
            get {
                return ResourceManager.GetString("ConversionTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert from base currency.
        /// </summary>
        public static string ConvertFromBase {
            get {
                return ResourceManager.GetString("ConvertFromBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Calculator.
        /// </summary>
        public static string CreditCalculatorButtonText {
            get {
                return ResourceManager.GetString("CreditCalculatorButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit calculator:.
        /// </summary>
        public static string CreditCalculatorHeader {
            get {
                return ResourceManager.GetString("CreditCalculatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Calculator.
        /// </summary>
        public static string CreditCalculatorPageHeader {
            get {
                return ResourceManager.GetString("CreditCalculatorPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention on these limits:.
        /// </summary>
        public static string CriticalLimitsHeader {
            get {
                return ResourceManager.GetString("CriticalLimitsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency:.
        /// </summary>
        public static string CurrencyHeader {
            get {
                return ResourceManager.GetString("CurrencyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CurrentButtonText {
            get {
                return ResourceManager.GetString("CurrentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: &apos;{0}&apos; successfully saved to &apos;D:\HomeManager&apos; directory..
        /// </summary>
        public static string DataExportCompleteMessage {
            get {
                return ResourceManager.GetString("DataExportCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        public static string DataExportPageTitle {
            get {
                return ResourceManager.GetString("DataExportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DayLable {
            get {
                return ResourceManager.GetString("DayLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default currency:.
        /// </summary>
        public static string DefaultCurrencyHeader {
            get {
                return ResourceManager.GetString("DefaultCurrencyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default operations filter:.
        /// </summary>
        public static string DefaultOperationFilterHeader {
            get {
                return ResourceManager.GetString("DefaultOperationFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string DefaultsTabHeader {
            get {
                return ResourceManager.GetString("DefaultsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Calculator.
        /// </summary>
        public static string DepositCalculatorButtonText {
            get {
                return ResourceManager.GetString("DepositCalculatorButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit calculator:.
        /// </summary>
        public static string DepositCalculatorHeader {
            get {
                return ResourceManager.GetString("DepositCalculatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Calculator.
        /// </summary>
        public static string DepositCalculatorPageHeader {
            get {
                return ResourceManager.GetString("DepositCalculatorPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit:.
        /// </summary>
        public static string DepositHeader {
            get {
                return ResourceManager.GetString("DepositHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly deposit:.
        /// </summary>
        public static string DepositMonthHeader {
            get {
                return ResourceManager.GetString("DepositMonthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionHeaer {
            get {
                return ResourceManager.GetString("DescriptionHeaer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadButtonText {
            get {
                return ResourceManager.GetString("DownloadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed successfully..
        /// </summary>
        public static string DownloadCompleteMessage {
            get {
                return ResourceManager.GetString("DownloadCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed. Bad internet connection or remote server doesn&apos;t responde or data is broken..
        /// </summary>
        public static string DownloadErrorMessage {
            get {
                return ResourceManager.GetString("DownloadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Error!.
        /// </summary>
        public static string DownloadFailedCaption {
            get {
                return ResourceManager.GetString("DownloadFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from SkyDrive failed. Local storage for application is broken. Please, reinstall the application..
        /// </summary>
        public static string DownloadFailedMessage {
            get {
                return ResourceManager.GetString("DownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore data from SkyDrive:.
        /// </summary>
        public static string DownloadHeader {
            get {
                return ResourceManager.GetString("DownloadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading information....
        /// </summary>
        public static string DownloadProgressMessage {
            get {
                return ResourceManager.GetString("DownloadProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string EnterButtonText {
            get {
                return ResourceManager.GetString("EnterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Categories.
        /// </summary>
        public static string ExpenseCategoriesTabHeader {
            get {
                return ResourceManager.GetString("ExpenseCategoriesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string ExpenseHeaer {
            get {
                return ResourceManager.GetString("ExpenseHeaer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string ExpenseTabHeader {
            get {
                return ResourceManager.GetString("ExpenseTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportButtonText {
            get {
                return ResourceManager.GetString("ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First payment:.
        /// </summary>
        public static string FirstPaymentHeader {
            get {
                return ResourceManager.GetString("FirstPaymentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string FoodCategoryName {
            get {
                return ResourceManager.GetString("FoodCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPasswordHeader {
            get {
                return ResourceManager.GetString("ForgotPasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string FromHeader {
            get {
                return ResourceManager.GetString("FromHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full price:.
        /// </summary>
        public static string FullPriceHeader {
            get {
                return ResourceManager.GetString("FullPriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        public static string IconHeader {
            get {
                return ResourceManager.GetString("IconHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversions.
        /// </summary>
        public static string IncludeConversions {
            get {
                return ResourceManager.GetString("IncludeConversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string IncludeExpenses {
            get {
                return ResourceManager.GetString("IncludeExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomes.
        /// </summary>
        public static string IncludeIncomes {
            get {
                return ResourceManager.GetString("IncludeIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Categories.
        /// </summary>
        public static string IncomeCategoriesTabHeader {
            get {
                return ResourceManager.GetString("IncomeCategoriesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string IncomeHeader {
            get {
                return ResourceManager.GetString("IncomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string IncomeTabHeader {
            get {
                return ResourceManager.GetString("IncomeTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed. Bad internet connection or remote server doesn&apos;t responde..
        /// </summary>
        public static string InitializeErrorMessage {
            get {
                return ResourceManager.GetString("InitializeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization....
        /// </summary>
        public static string InitializeProgressMessage {
            get {
                return ResourceManager.GetString("InitializeProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability:.
        /// </summary>
        public static string IsPossibleHeader {
            get {
                return ResourceManager.GetString("IsPossibleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit this account.
        /// </summary>
        public static string LimitAccountHeader {
            get {
                return ResourceManager.GetString("LimitAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit this category.
        /// </summary>
        public static string LimitCategoryHeader {
            get {
                return ResourceManager.GetString("LimitCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit:.
        /// </summary>
        public static string LimitHeader {
            get {
                return ResourceManager.GetString("LimitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit information:.
        /// </summary>
        public static string LimitInformationHeader {
            get {
                return ResourceManager.GetString("LimitInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LogInPageHeader {
            get {
                return ResourceManager.GetString("LogInPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homemanager.wp@gmail.com.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your suggestions or bug descriptions..
        /// </summary>
        public static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total month expense:.
        /// </summary>
        public static string MonthExpenseHeader {
            get {
                return ResourceManager.GetString("MonthExpenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total month income:.
        /// </summary>
        public static string MonthIncomeHeader {
            get {
                return ResourceManager.GetString("MonthIncomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string OkCaption {
            get {
                return ResourceManager.GetString("OkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string OperationPageTitle {
            get {
                return ResourceManager.GetString("OperationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operations .
        /// </summary>
        public static string OperationsLabel {
            get {
                return ResourceManager.GetString("OperationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsButtonText {
            get {
                return ResourceManager.GetString("OptionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsPageTitle {
            get {
                return ResourceManager.GetString("OptionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        public static string PasswordHeader {
            get {
                return ResourceManager.GetString("PasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string PasswordPageHeader {
            get {
                return ResourceManager.GetString("PasswordPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly payment:.
        /// </summary>
        public static string PaymentMonthHeader {
            get {
                return ResourceManager.GetString("PaymentMonthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent (%):.
        /// </summary>
        public static string PercentHeader {
            get {
                return ResourceManager.GetString("PercentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period (month):.
        /// </summary>
        public static string PeriodHeader {
            get {
                return ResourceManager.GetString("PeriodHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persentage:.
        /// </summary>
        public static string PersentageLabel {
            get {
                return ResourceManager.GetString("PersentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per unit.
        /// </summary>
        public static string PerUnitHeader {
            get {
                return ResourceManager.GetString("PerUnitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        public static string PreviewHeader {
            get {
                return ResourceManager.GetString("PreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ProtectButtonText {
            get {
                return ResourceManager.GetString("ProtectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string ProtectionButtonText {
            get {
                return ResourceManager.GetString("ProtectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, fill all fields and make sure, that password and confirmation are equal..
        /// </summary>
        public static string ProtectionFormErrorLabel {
            get {
                return ResourceManager.GetString("ProtectionFormErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect with password.
        /// </summary>
        public static string ProtectWithPassword {
            get {
                return ResourceManager.GetString("ProtectWithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter question:.
        /// </summary>
        public static string QuestionHeader {
            get {
                return ResourceManager.GetString("QuestionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate:.
        /// </summary>
        public static string RateHeader {
            get {
                return ResourceManager.GetString("RateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load rates automatically.
        /// </summary>
        public static string RatesAutoUpdate {
            get {
                return ResourceManager.GetString("RatesAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        public static string RatesButtonText {
            get {
                return ResourceManager.GetString("RatesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed. Can&apos;t process received information, due to incorrect data format..
        /// </summary>
        public static string RatesFormatErrorMessage {
            get {
                return ResourceManager.GetString("RatesFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        public static string RatesPageTitle {
            get {
                return ResourceManager.GetString("RatesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading rates....
        /// </summary>
        public static string RatesProgressMessage {
            get {
                return ResourceManager.GetString("RatesProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed. Bad internet connection or server doesn&apos;t responde..
        /// </summary>
        public static string RatesWebErrorMessage {
            get {
                return ResourceManager.GetString("RatesWebErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaches limit in.
        /// </summary>
        public static string ReachLimitText {
            get {
                return ResourceManager.GetString("ReachLimitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string ReachLimitTextDaysPart {
            get {
                return ResourceManager.GetString("ReachLimitTextDaysPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to remove account &apos;{0}&apos; and {1} related operations?.
        /// </summary>
        public static string RemoveAccountMessage {
            get {
                return ResourceManager.GetString("RemoveAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to remove category &apos;{0}&apos; and {1} related operations?.
        /// </summary>
        public static string RemoveCategoryMessage {
            get {
                return ResourceManager.GetString("RemoveCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RestoreButtonText {
            get {
                return ResourceManager.GetString("RestoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string ResultHeader {
            get {
                return ResourceManager.GetString("ResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string SalaryCategoryName {
            get {
                return ResourceManager.GetString("SalaryCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data to export:.
        /// </summary>
        public static string SelectDataHeader {
            get {
                return ResourceManager.GetString("SelectDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string SellHeader {
            get {
                return ResourceManager.GetString("SellHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDrive.
        /// </summary>
        public static string SkyDriveButtonText {
            get {
                return ResourceManager.GetString("SkyDriveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDrive.
        /// </summary>
        public static string SkyDrivePageTitle {
            get {
                return ResourceManager.GetString("SkyDrivePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating information....
        /// </summary>
        public static string SkyDriveProgressText {
            get {
                return ResourceManager.GetString("SkyDriveProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsButtonText {
            get {
                return ResourceManager.GetString("StatisticsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsPageTitle {
            get {
                return ResourceManager.GetString("StatisticsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string ToHeader {
            get {
                return ResourceManager.GetString("ToHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsButtonText {
            get {
                return ResourceManager.GetString("ToolsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsPageHeader {
            get {
                return ResourceManager.GetString("ToolsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount: .
        /// </summary>
        public static string TotalAmountHeader {
            get {
                return ResourceManager.GetString("TotalAmountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string TransportCategoryName {
            get {
                return ResourceManager.GetString("TransportCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypeHeader {
            get {
                return ResourceManager.GetString("TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uid.
        /// </summary>
        public static string UidHeader {
            get {
                return ResourceManager.GetString("UidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units per.
        /// </summary>
        public static string UnitsPerHeader {
            get {
                return ResourceManager.GetString("UnitsPerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string UpdateButtonText {
            get {
                return ResourceManager.GetString("UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadButtonText {
            get {
                return ResourceManager.GetString("UploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload completed successfully..
        /// </summary>
        public static string UploadCompleteMessage {
            get {
                return ResourceManager.GetString("UploadCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading failed. Bad internet connection or remote server doesn&apos;t responde..
        /// </summary>
        public static string UploadErrorMessage {
            get {
                return ResourceManager.GetString("UploadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload data to SkyDrive:.
        /// </summary>
        public static string UploadHeader {
            get {
                return ResourceManager.GetString("UploadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading information....
        /// </summary>
        public static string UploadProgressMessage {
            get {
                return ResourceManager.GetString("UploadProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage statistics for last month:.
        /// </summary>
        public static string UsageStatisticsHeader {
            get {
                return ResourceManager.GetString("UsageStatisticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password. Please, try again or click &apos;Restore&apos; button..
        /// </summary>
        public static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
    }
}
